inp = input("Enter a sentence ")

num_c = sum(c.isdigit() for c in inp)
up_c = sum(c.isupper() for c in inp)
low_c = sum(c.islower() for c in inp)
other_c = len(inp) - (num_c + up_c + low_c)
print("number of numbers:", num_c)
print("number of uppercase letters:", up_c)
print("number of lowercase letters:", low_c)
print("number of other characters:", other_c)
